before_install:
  - git submodule sync
  - git submodule update --init --recursive --remote
  - rm -rf public
  - cd ../.. ; cd themes/hugo-primer; git checkout master

install:
  - apt-get install hugo

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  target_branch: gh-pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
