before_install:
  - rm -rf public
  - mkdir themes; cd themes; git clone https://github.com/keaising/hugo-primer.git

install:
  - apt-get install hugo

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  target_branch: gh-pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
