branches:
  only:
  - source

before_install:
  - rm -rf public
  - rm -rf themes
  - git clone https://github.com/keaising/kitto.git themes/kitto

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_0.58.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - rm hugo*.deb

script:
  - hugo version
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  target_branch: master
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: source

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
