git:
  submodule: false

before_install:
  - rm -rf public
  - rm -rf themes
  - mkdir themes; cd themes; git clone https://github.com/keaising/hugo-primer.git

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_0.58.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - rm hugo*.deb

script:
  - hugo version
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  repo: keaising/keaising.github.io
  target_branch: gh-pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
