markdown: rdiscount
highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "流水沉微"
markdown: kramdown

author: "Shuxiao Wang"
atom-baseurl: "https://shuxiao.wang"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /index.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: Eureka!
    class: fa fa-tasks
    href: /eureka.html
  - title: About
    class: fa fa-user
    href: /about.html
#  - title: Blogroll
#    class: fa fa-link
#    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

collections:
  leetcode:
    name: LeetCode
    url: leetcode
    output: true
    permalink: /:collection/:title
    sort_by: date
  cs:
    name: CS
    url: cs
    output: true
    permalink: /:collection/:title
    sort_by: date
