baseURL = "http://shuxiao.wang"
title = "流水沉微"
theme = "kitto"

languageCode = "cn"
hasCJKLanguage = true
pygmentsCodeFences = true
disableFastRender = true
pygmentsUseClasses = true

# You can use favicon by addin them manually.
useIcon = true
